package model;

import model.common.EmployeeAM;

import oracle.jbo.server.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Oct 22 13:13:29 EDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeeAMImpl extends ApplicationModuleImpl implements EmployeeAM {
    /**
     * This is the default constructor (do not remove).
     */
    public EmployeeAMImpl() {
    }

    /**
     * Container's getter for EmployeeVO.
     * @return EmployeeVO
     */
    public EmployeeVOImpl getEmployeeVO() {
        return (EmployeeVOImpl) findViewObject("EmployeeVO");
    }

    public void getEmployees(int numberOfEmployee) {
        System.err.println(numberOfEmployee);
        EmployeeVOImpl empl = getEmployeeVO();
        empl.createEmployees(numberOfEmployee);
    }
}

