package model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Oct 22 13:20:04 EDT 2016
// ---------------------------------------------------------------------
public interface EmployeeAM extends ApplicationModule {
    void getEmployees(int numberOfEmployee);
}

